# permissions for end users to edit imagebuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagebuilder-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: osbuild-operator
    app.kubernetes.io/part-of: osbuild-operator
    app.kubernetes.io/managed-by: kustomize
  name: imagebuilder-editor-role
rules:
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilders/status
  verbs:
  - get
