---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilderimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilderimages/finalizers
  verbs:
  - update
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilderimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilders/finalizers
  verbs:
  - update
- apiGroups:
  - osbuild.rh-ecosystem-edge.io
  resources:
  - imagebuilders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
